// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/PabloPie/Gandi-Go/client (interfaces: V4Caller)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockV4Caller is a mock of V4Caller interface
type MockV4Caller struct {
	ctrl     *gomock.Controller
	recorder *MockV4CallerMockRecorder
}

// MockV4CallerMockRecorder is the mock recorder for MockV4Caller
type MockV4CallerMockRecorder struct {
	mock *MockV4Caller
}

// NewMockV4Caller creates a new mock instance
func NewMockV4Caller(ctrl *gomock.Controller) *MockV4Caller {
	mock := &MockV4Caller{ctrl: ctrl}
	mock.recorder = &MockV4CallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockV4Caller) EXPECT() *MockV4CallerMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockV4Caller) Send(arg0 string, arg1 []interface{}, arg2 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send
func (mr *MockV4CallerMockRecorder) Send(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockV4Caller)(nil).Send), arg0, arg1, arg2)
}
