package hosting

// DiskManager represents a service capable of manipulating Gandi Disks
type DiskManager interface {
	// CreateDisk creates a Disk object from a given DiskSpec
	//
	// It can only be a data Disk, to create an OS Disk, use
	// CreateDiskFromImage
	CreateDisk(disk DiskSpec) (Disk, error)

	// CreateDiskFromImage creates a Disk from a Gandi DiskImage
	//
	// A new size for the disk can be specified, but both disks
	// must reside in the same Region, this means that the DiskSpec's
	// `RegionID` must be the same as DiskImage's
	CreateDiskFromImage(disk DiskSpec, src DiskImage) (Disk, error)

	// ListAllDisks return a list with every Disk the user has,
	// independently of the Region it is in
	//
	// See ListDisks for filtering options
	ListAllDisks() ([]Disk, error)

	// DiskFromName returns a Disk whose name matches `name`,
	// if no Disk is found or there was an error making the request,
	// an empty Disk is returned
	DiskFromName(name string) Disk

	// ListDisks return a list of Disks, filtered with the options
	// given in the DiskFilter
	//
	// An unset field in `diskFilter` is ignored when making the
	// request
	ListDisks(diskFilter DiskFilter) ([]Disk, error)

	// DeleteDisk deletes the Disk given, provided it has
	// a valid ID
	//
	// If the operation was successful a nil error is returned
	DeleteDisk(disk Disk) error

	// ExtendDisk extends the given Disk by `size`, this means
	// that if the original size was X, the new size will be
	// X+size, size being in GB
	ExtendDisk(disk Disk, size uint) (Disk, error)

	// RenameDisk renames the given Disk with the name provided
	RenameDisk(disk Disk, name string) (Disk, error)
}

// Disk is a Gandi disk object
type Disk struct {
	// ID of the object in the API
	ID string

	// Name of the disk
	Name string

	// Size in GB
	Size int

	// ID of the Region the disk resides in
	RegionID string

	// State of the disk:
	// being_created, created, rollback, paused,
	// being_migrated, redemption, deleted
	State string

	// Type of disk:
	// system, image, data, backup, snapshot
	Type string

	// List of VMs the disk is attached to
	VM []string

	// Set to true if the disk is attached to
	// a VM and used as boot device
	BootDisk bool
}

// DiskSpec contains the parameters to create a new Disk
//
// The only mandatory field is `RegionID`, a name will
// automatically be generated by Gandi's API and its size
// will default to 10 GB if not provided
type DiskSpec struct {
	RegionID string
	Name     string

	// A Disk size is given in GB
	// The Disk wont be able to shrink in size,
	// only increase
	Size int
}

// DiskFilter is a struct to define filtering criteria
// for listing Disk objects
//
// TODO: allow a list of elements
type DiskFilter struct {
	ID       string
	RegionID string
	Name     string
	VMID     string
}
